# Generated by Django 5.2.3 on 2025-07-01 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_events_organizer_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'permissions': [('can_register', 'Determine whether a user can register'), ('view_own_registration', 'Determine whether a user can view his own registration'), ('view_attendee', 'Determine whether a user can view attendee at their own events')]},
        ),
    ]
