# Generated by Django 5.2.3 on 2025-07-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_events_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.CharField(default='a', max_length=300),
            preserve_default=False,
        ),
    ]
