# Generated by Django 5.2.3 on 2025-07-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_registration_checked_in'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'permissions': [('can_register', 'Determine whether a user can register'), ('view_own_registration', 'Determine whether a user can view his own registration'), ('view_attendee', 'Determine whether a user can view attendee at their own events'), ('scan_ticker', 'organizer that can scan ticket')]},
        ),
    ]
